# Generated by Django 4.2.16 on 2024-12-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('general_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Wages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('wage', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
